#!/bin/bash
set -euo pipefail

# ============================================================
# 06-filament-autogenerated.sh — Laravel + Filament, данные админа генерируются
# ============================================================
# Сценарий:
#   Сайт с админ-панелью Filament. Указан только email администратора,
#   имя и пароль генерирует скрипт.
#
# Что получится:
#   - composer require filament/filament:"^5.0", затем
#     artisan filament:install --panels и artisan make:filament-user;
#   - панель https://cms.example.com/admin;
#   - имя (8 символов a-f0-9) и пароль (10 символов a-zA-Z0-9) выводятся
#     в консоль и дописываются в /var/www/cms/.env как FILAMENT_ADMIN_*.
#
# Важно:
#   - --filament-email проверяется сразу при старте;
#   - ошибка на шагах Filament (в том числе из-за упавших миграций)
#     останавливает скрипт до перезапуска nginxproxy и получения SSL;
#   - проверьте, что Filament 5 совместим с выбранной версией Laravel
#     (по умолчанию --laravel-version 13.0).
#
# Перед запуском поменяйте: slug, домен и оба email.
#
# Запуск на сервере (из любой папки):
#   bash /opt/laravel-deploy/examples/06-filament-autogenerated.sh
# DEPLOY_DIR по умолчанию — папка laravel-deploy, в которой лежит этот пример
# (deploy-laravel.sh, laravel/, nginxproxy/). Переопределение:
#   DEPLOY_DIR=/srv/laravel-deploy bash 06-filament-autogenerated.sh
# ============================================================

DEPLOY_DIR="${DEPLOY_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

sudo bash "$DEPLOY_DIR/deploy-laravel.sh" \
  --slug cms \
  --domain cms.example.com \
  --db-type postgres \
  --install-filament \
  --filament-email admin@example.com \
  --ssl-email admin@example.com
