#!/bin/bash
set -euo pipefail

# ============================================================
# 06-filament-autogenerated.sh — Laravel + Filament, admin credentials generated
# ============================================================
# Scenario:
#   A site with the Filament admin panel. Only the administrator's email is given;
#   the script generates the name and password.
#
# Result:
#   - composer require filament/filament:"^5.0", then
#     artisan filament:install --panels and artisan make:filament-user;
#   - the panel https://cms.example.com/admin;
#   - the name (8 characters a-f0-9) and password (10 characters a-zA-Z0-9) are printed
#     to the console and appended to /var/www/cms/.env as FILAMENT_ADMIN_*.
#
# Important:
#   - --filament-email is validated right at startup;
#   - an error in the Filament steps (including failed migrations)
#     stops the script before the nginxproxy restart and SSL issuance;
#   - check that Filament 5 is compatible with the chosen Laravel version
#     (--laravel-version 13.0 by default).
#
# Before running, change: the slug, domain and both emails.
#
# Run on the server (from any folder):
#   bash /opt/laravel-deploy/examples/06-filament-autogenerated.sh
# DEPLOY_DIR defaults to the laravel-deploy folder that contains this example
# (deploy-laravel.sh, laravel/, nginxproxy/). To override:
#   DEPLOY_DIR=/srv/laravel-deploy bash 06-filament-autogenerated.sh
# ============================================================

DEPLOY_DIR="${DEPLOY_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

sudo bash "$DEPLOY_DIR/deploy-laravel.sh" \
  --slug cms \
  --domain cms.example.com \
  --db-type postgres \
  --install-filament \
  --filament-email admin@example.com \
  --ssl-email admin@example.com
